### ISSUE TITLE
Difficulty cross-compiling with autoconf 2.71

### ISSUE THREAD

**Issue by calebzulawski** [FFTW/fftw3#312]
With autoconf 2.69, I can configure with `--host aarch64-unknown-linux-gnu` and set `CC`, `CFLAGS`, etc for my cross-compiler and everything works as expected.

With autoconf 2.71, it appears that `CFLAGS` is not passed to `libtool`, which results in breaking my cross-compiler.  Specifically, I'm losing `CFLAGS=--target=aarch64-unknown-linux-gnu` and I get various neon errors.

I'm using FFTW 3.3.10.

**Comment by matteo-frigo** [comment]
It's hard for me to offer useful advice given the information you provide.

Can you give me a specific set of instructions to reproduce the problem?  Something like

install debian bullseye
apt install build-essential crossbuild-essential-arm64
./configure --foo --bar

**Comment by matteo-frigo** [comment]
Specifically, the usual way to cross-compile is something like

./configure --host=aarch64-linux-gnu CFLAGS='-g'

which works for me, in the sense that it uses '-g' as CFLAGS.  I have never seen CFLAGS=--target=... and I have no idea what it does and why it would have ever worked.

**Comment by calebzulawski** [comment]
`--target` is clang's flag for specifying the target.  I don't have a public Linux sysroot handy, but the following on macOS produces the same error:
```
brew install autoconf
autoreconf -i
CC=clang CFLAGS="--target=arm64-apple-macos --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk" ./configure --host=aarch64-apple-macos --enable-neon
make
```
On Linux, replace the targets and sysroot but otherwise it's the same invocation.  The following error (and many like it) are emitted:
```
Making all in neon
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
/bin/sh ../../../libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I. -I../../..  -I ../../..   -O3 -fomit-frame-pointer -mtune=native -fstrict-aliasing -MT n1fv_2.lo -MD -MP -MF .deps/n1fv_2.Tpo -c -o n1fv_2.lo n1fv_2.c
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../../.. -I ../../.. -O3 -fomit-frame-pointer -mtune=native -fstrict-aliasing -MT n1fv_2.lo -MD -MP -MF .deps/n1fv_2.Tpo -c n1fv_2.c -o n1fv_2.o
In file included from n1fv_2.c:3:
In file included from ./../common/n1fv_2.c:70:
In file included from ../../../dft/simd/n1f.h:21:
../../../simd-support/simd-neon.h:25:2: error: "NEON only works in single precision on 32 bits ARM"
#error "NEON only works in single precision on 32 bits ARM"
 ^
../../../simd-support/simd-neon.h:47:2: error: "compiling simd-neon.h requires -mfpu=neon or equivalent"
#error "compiling simd-neon.h requires -mfpu=neon or equivalent"
 ^
 ```
The `CFLAGS` environment variable is not propagated, I assume this isn't particular to clang but to this version of autoconf, since it works with 2.69.

**Comment by matteo-frigo** [comment]
But your command line works for me on linux:

```
athena@amd:~$ clang --version
Debian clang version 14.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

athena@amd:fftw3$ CC=clang CFLAGS="-O" ./configure --host=aarch64-apple-macos --enable-neon
```

and I see the -O CFLAGS being used.  (My clang does not support --target).

So you will have to dig deeper, since I don't have a macos machine available.
Can you try

./configure CFLAGS="..." 

Maybe the shell is not passing CFLAGS in the environment or something.  (I use bash on linux.)

**Comment by calebzulawski** [comment]
That's a good suggestion, I tried moving `CC` and `CFLAGS` after `configure` as you suggested, but it still produces the same error. I also tried setting those variables for `make`, though it should be unnecessary.  Did you forget to run `autoreconf -i`?  I just ran the following on Debian Sid (in a fresh docker instance):
```
apt-get update && apt-get -y install autoconf clang crossbuild-essential-arm64 libtool curl
curl https://www.fftw.org/fftw-3.3.10.tar.gz -o fftw.tar.gz
tar -xf fftw.tar.gz
cd fftw-3.3.10
autoreconf -i
./configure --host=aarch64-unknown-linux-gnu --enable-neon CC=clang CFLAGS="--target=aarch64-unknown-linux-gnu -fuse-ld=/usr/bin/aarch64-linux-gnu-ld" 
make
```
This exact sequence reproduces the same error from above on Linux.

**Comment by matteo-frigo** [comment]
Ah, I forgot about this.  I was compiling from github head and not fftw-3.3.10.  This issue was fixed in 619564efbf84199f87e1a3047da00b600208fca2 and the 3.3.10 release does not work with autoconf 2.71, as you point out.

Just grab configure.ac from github if you need the newer autoconf.

See https://github.com/FFTW/fftw3/pull/271 and references therein.

**Comment by matteo-frigo** [comment]
You also need to grab the new m4/ax_cc_maxopt.m4 for autoconf 2.71
